### ISSUE TITLE
Dial froze in Macros menu, and now appears to be dead

### ISSUE THREAD

**Issue by shampeon** [bdring/FluidDial#14]
FluidNC 3.7.18
Latest master from FluidDial

After checking and double-checking I got all the pins/cables wired correctly, I got the Dial working this afternoon, and was able to home and jog.

I was checking out the various menus, and selected Macros. I don't have any macros defined in FluidNC. At that point, the Dial froze, and I was unable to exit the Macros menu. Meaning, the M5 bezel button, touchscreen, or physical buttons didn't do anything. The touchscreen was illuminated but frozen on "Reading Macros". I unplugged the Dial, and then plugged it back in to see if it would reset. Now the Dial won't boot, and is unresponsive when powered either through the cable or USB-C.

I can see that the Dial is receiving power, as there's a red light visible within the Dial when powered by the 2 pin cable or USB-C.

I tried plugging it into my desktop to reflash, but the port doesn't come up.

~~~yaml
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1

uart_channel1:
  report_interval_ms: 75
  uart_num: 1
~~~

**Comment by shampeon** [comment]
Just removed the Stamp S3, and plugged into USB-C it's still unresponsive, and now hot to the touch.

**Comment by shampeon** [comment]
...and my FluidNC controller is apparently dead. What in the heck happened?

I buzzed out the wiring to make sure there were no shorts, and tested it disconnected from the M5 Dial to make sure it was getting 24V on the right cables.
![IMG_5577](https://github.com/user-attachments/assets/dfd5b9e4-170d-44f8-9f3d-842b36872c8b)

**Comment by MitchBradley** [comment]
My guess is an intermittent ground connection that resulting in the 24V supply returning through the rx/tx lines.

**Comment by shampeon** [comment]
Is that something that could have been prevented with an optoisolator board?

**Comment by MitchBradley** [comment]
optical isolation is one of many ways to prevent it.

**Comment by shampeon** [comment]
I was pretty careful with this build (e.g. I knew that FluidNC tx <-> Dial rx, and Dial tx <-> rx, and getting this wrong could be catastrophic, so I verified everything with a multimeter), highlighted in the caveats in the docs, but techniques to isolate the tx/rx would have been good information to have before even trying this. My controller is cooked, as is my dial.

**Comment by MitchBradley** [comment]
> techniques to isolate the tx/rx would have been good information to have before even trying this. My controller is cooked, as is my dial.

Responses to implied criticism:
1. This is a DIY thing, early in its lifetime.  We didn't realize it was going to be so fragile until people started blowing up things due to miswiring.  Hindsight is 20/20
2. Having learned some of the pitfalls, Bart now sells a connection kit with protection and we do not recommend or support not using it.  Early on, I did my own version of a connection kit but abandoned it because I realized that finishing it and supporting it would be a money-losing proposition for me as, unlike Bart, I am not set up for selling hardware.  Some of the concepts of my kit made it into Bart's design.
3. I have never blown up anything despite having made 4 dials.  Perhaps it is because I have always powered mine from 5V instead of higher voltages.  The only way to get 5V into an M5 Dial is via the USB-C connector which is a bit more trouble, DIY-wise, than the screw terminal connector.  I made a PCB with a USB-C male and other relevant connectors, but it is possible to buy USB-C male breakouts for point to point wiring.
4. You are welcome to edit the wiki to add additional warnings or instructional material about isolation techniques and their tradeoffs, limitations, and implementation methods.  I don't feel inclined to do so, preferring to waste my time on other aspects of this extensive project that generates an extraordinary number of requests for support, debugging of hardware that we do neither control nor benefit from, and new features for one-off use cases.  Meanwhile the donation rate is sufficient to buy one breakfast per month at the local diner.

**Comment by shampeon** [comment]
Mitch, I did volunteer my time to try to improve the FluidNC wiki docs earlier this year, until it was made pretty clear by you that I was wasting your time when I tried to get clarification on info in the docs that you understood but I didn't. That is an impossible set of conflicting attitudes to resolve--better docs means fewer support requests and more time for development on your part--so I stepped away, as you're not the only one with time scarcity.

I don't know if this will mean anything to you, as you have already decided that I'm being unreasonable, but on point 4, if this was knowledge that I possessed, would I have had the problem I encountered? Where would I have reasonably found this information when I decided to make one of these pendants? If you read the wiki page as it exists right now, would you conclude that the only recommended way of adding this pendant is to purchase one of Bart's connection kits?

Anyway, the issue appears to not be a software problem, so I'll close this, and wish you well in growing your community.
